### ISSUE TITLE
Detailed spec

### ISSUE THREAD

**Issue by med4kat** [med4kat/Digineed#1]
Linn,

Could you please provide detailed spec?

You can either attach the doc here or instruct how to get it.

**Comment by ihlonne** [comment]
![digineedsspecs](https://user-images.githubusercontent.com/88430256/169609932-19402d01-3e51-497f-a622-fc7a76970d7c.png)

**Comment by ihlonne** [comment]
Gradient (lighter blue) -  #6AB9D9
Gradient (darker blue) -  #5670BF 

Text colour (dark grey) - #0D0D0D
Text colour (white) - #FFFFFF

Submit BG (pale blue) - #D5EAF2
Button border (blue) - #4563BF

**Comment by med4kat** [comment]
Many thanks!
