### ISSUE TITLE
Review code

### ISSUE THREAD

**Issue by med4kat** [med4kat/Digineed#17]
Please review code and edit/comment by midnight 23 May. 
Thanks!

**Comment by LiamBarnard** [comment]
Code reviewed and  PR sent. Full list of issues addressed:
-Logo left and Contact span are right against page border (personal opinion, so I won't change, we can discuss at next meeting)
-H1 Element can be in 1 line of code to save space and have neat code, currently spans 3 lines of code
-A page can only have 1 H1 Element which is right at the top, so the projects lower down should be H2/H3 or whatever
-The about us section with our names in Divs seems a bit pointless, in my update I'll change the div out for H2
-The classes of some of the divs are a bit non specific if you dial into the CSS without the HTML code, the circles for example where our faces will be could be in a div class="photo-circle" or something more specific

**Comment by med4kat** [comment]
Thank you guys!
