### ISSUE TITLE
Add logo

### ISSUE THREAD

**Issue by ihlonne** [med4kat/Digineed#18]
Logo needs to be added.

![digi-need-logo-white](https://user-images.githubusercontent.com/88430256/169813357-7232df3f-a651-40c0-ba10-3b2fb4dee77c.png)

**Comment by ihlonne** [comment]
Note: Logo is added to the comment above, it's just white text with a transparent background.

**Comment by med4kat** [comment]
![digi-need-logo-white](https://user-images.githubusercontent.com/31211139/169814446-fcecff70-88c0-43ba-99d5-69b5d8488c24.png)
